[Desktop Entry]
Name=System Profiler and Benchmark
Name[ko]=하드웨어 정보
Name[de]=System Profiler und Benchmark
Name[es]=Informacion y Rendimiento del Sistema
Name[fr]=Informations et Benchmarks du Système
Name[pt_BR]=Informações e Testes do Sistema
Name[ru]=Информация о системе и тестирование
Name[tr]=Sistem Bilgisi ve Karşılaştırma
Comment=Displays system information
Comment[ko]=시스템 및 하드웨어 정보 보기 및 벤치마크
Comment[de]=Anzeigen von Systeminformationen
Comment[ru]=Показывает информацию о системе
Exec=@CMAKE_INSTALL_FULL_BINDIR@/hardinfo
Icon=hardinfo
Terminal=false
Type=Application
StartupNotify=true
Categories=System;
Keywords=linux;kernel;system;hardware;cpu;processor;capabilities;frequency;memory;ram;board;resources;sensors;devices;usb;pci;display;network;benchmark;test;
